name: Deploy Vite to GitHub Pages

on:
  # Trigger the workflow on push to the main branch
  push:
    branches:
      - main  # Change this to your default branch if needed
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'  # Specify the version of Node.js
          cache: 'npm'  # Cache npm dependencies

      - name: Install dependencies
        run: npm ci  # Use npm ci for consistent installs based on package-lock.json

      - name: Build project
        run: npm run build  # Ensure your Vite configuration is correct

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'  # Path to the directory where Vite outputs the build

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
